name: Publish Website
on:
  push:
    branches:
      - main
    paths:
      - "packages/lambdas/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/lambdas
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js and yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: packages/lambdas/yarn.lock
      - name: Install Modules
        run: yarn
      - name: Build
        run: yarn build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: eu-west-2
      - name: Copy files to the production bucket with the AWS CLI
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_LAMBDAS_BUCKET }} --delete --acl public-read
