name: Rollback MYSQL

on:
  workflow_dispatch:
    inputs:
      count:
        type: string
        description: Amount of changes to rollback
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: liquibase-github-actions/rollback-count@v4.25.1
        with:
          count: ${{ github.event.inputs.count }}
          driver: com.mysql.cj.jdbc.Driver
          classpath: packages/mysql/lib/mysql-connector-j-8.0.33.jar
          changelogFile: "changelog.xml"
          url: ${{ secrets.MYSQL_URL }}
          username: ${{ secrets.MYSQL_USERNAME }}
          password: ${{ secrets.MYSQL_PASSWORD }}
          searchPath: packages/mysql
