name: Validate MYSQL

on:
  pull_request:
    paths:
      - "packages/mysql/**"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: liquibase-github-actions/validate@v4.25.1
        with:
          driver: com.mysql.cj.jdbc.Driver
          classpath: packages/mysql/lib/mysql-connector-j-8.0.33.jar
          changelogFile: "changelog.xml"
          url: ${{ secrets.MYSQL_URL }}
          username: ${{ secrets.MYSQL_USERNAME }}
          password: ${{ secrets.MYSQL_PASSWORD }}
          searchPath: packages/mysql
